### ISSUE TITLE
Gem depends on Trollop, but gem install doesn't load the dependency

### ISSUE THREAD

**Issue by hms** [hjdivad/git-topic#1]
gem install git-topic
git topic install-aliases errors with:

/Users/hal/.rvm/gems/ruby-1.9.2-rc1/gems/git-topic-0.1.4/bin/git-topic:4:in `require': no such file to load -- trollop (LoadError)

gem install trollop
git topic install aliases now works, so I'm assuming that's the issue

**Comment by hjdivad** [comment]
Should be fixed in 0.1.5 (although the dependency version numbers are probably not so accurate).
